/**
 * Single source of truth for brand contact details, social handles,
 * and legal entity info. Update values here once and they propagate
 * everywhere — Footer, Nav CTA, WhatsApp float, JSON-LD, email templates, etc.
 *
 * NOTE: Anything that should be editable by the client without a deploy
 * lives in Sanity (`siteSettings` document). This file is for things that
 * change rarely (legal entity, registered address) or are required at
 * build time (JSON-LD, sitemap).
 */

export const siteConfig = {
  // ─── Brand ─────────────────────────────────────────────────
  name: 'Jungla',
  legalName: 'PT Jungla Lombok',
  tagline: 'Luxury villa construction & management in Lombok, Indonesia.',
  description:
    'We design, build, and manage high-end villas in Lombok, Indonesia. Seamless investment and villa management with European standards.',

  // ─── URLs ──────────────────────────────────────────────────
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://jungla.com',
  // Auto-generated by src/app/opengraph-image.tsx
  ogImage: '/opengraph-image',

  // ─── Contact ───────────────────────────────────────────────
  // TODO(launch): replace placeholders with real values from client
  email: 'hello@jungla.com',
  emailNoReply: 'noreply@jungla.com',
  phone: '+62 812 3456 7890',
  // E.164 without + or spaces, used by wa.me links
  whatsapp: '6281234567890',
  whatsappMessage: "Hi Jungla! I found you on your website and I'd like to know more.",

  // ─── Social ────────────────────────────────────────────────
  social: {
    instagram: 'https://instagram.com/jungla.lombok',
    instagramHandle: '@jungla.lombok',
  },

  // ─── Address (used in JSON-LD + Footer) ────────────────────
  address: {
    locality: 'Kuta',
    region: 'Lombok Tengah',
    country: 'ID',
    countryName: 'Indonesia',
  },
} as const

export type SiteConfig = typeof siteConfig
